  # Low-level details of the domain model. are specific to the target domain, and hence will contain specific information about manufacturing processes, resources, and so on. This information can be changed according to the specifications of the end-users 
# Created 2019-03-28 10:12:06.111932 

# Dict storing class info: 
classes = {'Experiments': {'description': 'tbd',
                 'label': 'TBox',
                 'optional_properties': [],
                 'required_properties': [],
                 'subclass_of': ['Activity'],
                 'uri': 'http://example.org/tbox/experiments',
                 'version': '3.2'},
 'Material': {'description': 'tbd',
              'label': 'TBox',
              'optional_properties': [],
              'required_properties': [],
              'subclass_of': ['Resource'],
              'uri': 'http://example.org/tbox/material',
              'version': '3.2'},
 'Measurements': {'description': 'tbd',
                  'label': 'TBox',
                  'optional_properties': [],
                  'required_properties': [],
                  'subclass_of': ['Activity'],
                  'uri': 'http://example.org/tbox/measurements',
                  'version': '3.2'},
 'Oven': {'description': 'tbd',
          'label': 'TBox',
          'optional_properties': [],
          'required_properties': [],
          'subclass_of': ['Resource'],
          'uri': 'http://example.org/tbox/oven',
          'version': '3.2'},
 'Part': {'description': 'tbd',
          'label': 'TBox',
          'optional_properties': [],
          'required_properties': [],
          'subclass_of': ['Resource'],
          'uri': 'http://example.org/tbox/part',
          'version': '3.2'},
 'ProductDesign': {'description': 'tbd',
                   'label': 'TBox',
                   'optional_properties': [],
                   'required_properties': [],
                   'subclass_of': ['Activity'],
                   'uri': 'http://example.org/tbox/productdesign',
                   'version': '3.2'},
 'Production': {'description': 'tbd',
                'label': 'TBox',
                'optional_properties': [],
                'required_properties': [],
                'subclass_of': ['Activity'],
                'uri': 'http://example.org/tbox/production',
                'version': '3.2'},
 'Project': {'description': 'An undertaking requiring concerted effort by Agents',
             'label': 'TBox',
             'optional_properties': [],
             'required_properties': [],
             'subclass_of': ['Activity'],
             'uri': 'http://example.org/tbox/project',
             'version': '3.2'},
 'Sensor': {'description': 'A system that transform a physical phenomenon into a digital representation',
            'label': 'TBox',
            'optional_properties': [],
            'required_properties': [],
            'subclass_of': ['System'],
            'uri': 'http://example.org/tbox/sensor',
            'version': '3.2'},
 'SimulatedSensor': {'description': 'A simulator that simulates a sensor: It transforms a simulated value into something that looks like sensor data',
                     'label': 'TBox',
                     'optional_properties': [],
                     'required_properties': [],
                     'subclass_of': ['Simulator'],
                     'uri': 'http://example.org/tbox/simulatedsensor',
                     'version': '3.2'},
 'Simulation': {'description': 'tbd',
                'label': 'TBox',
                'optional_properties': [],
                'required_properties': [],
                'subclass_of': ['Activity'],
                'uri': 'http://example.org/tbox/simulation',
                'version': '3.2'},
 'Simulator': {'description': 'A system that simulates a process and produces simulation results',
               'label': 'TBox',
               'optional_properties': [],
               'required_properties': [],
               'subclass_of': ['System'],
               'uri': 'http://example.org/tbox/simulator',
               'version': '3.2'},
 'Tool': {'description': 'tbd',
          'label': 'TBox',
          'optional_properties': [],
          'required_properties': [],
          'subclass_of': ['Resource'],
          'uri': 'http://example.org/tbox/tool',
          'version': '3.2'},
 'ToolDevelopment': {'description': 'tbd',
                     'label': 'TBox',
                     'optional_properties': [],
                     'required_properties': [],
                     'subclass_of': ['Activity'],
                     'uri': 'http://example.org/tbox/tooldevelopment',
                     'version': '3.2'},
 'VirtualSensor': {'description': 'A software system that simulates a sensor based on other sensed data and/or data models',
                   'label': 'TBox',
                   'optional_properties': [],
                   'required_properties': [],
                   'subclass_of': ['System'],
                   'uri': 'http://example.org/tbox/virtualsensor',
                   'version': '3.2'}}
