# The upper domain model is generic across different data management domain applications. 
# Created 2019-03-28 10:12:06.101889 

# Dict storing class info: 
classes = {'Activity': {'description': 'A frame for certain knowledge, like a project or a project phase',
              'label': 'TBox',
              'optional_properties': [],
              'required_properties': [],
              'subclass_of': ['KBMSThing'],
              'uri': 'http://example.org/tbox/activity',
              'version': '3.2'},
 'Agent': {'description': 'Things or people that can create knowledge, like users, organization, or systems',
           'label': 'TBox',
           'optional_properties': [],
           'required_properties': [],
           'subclass_of': ['KBMSThing'],
           'uri': 'http://example.org/tbox/agent',
           'version': '3.2'},
 'Data': {'description': 'A digital representation of knowledge',
          'label': 'TBox',
          'optional_properties': ['dcterms:subject'],
          'required_properties': [],
          'subclass_of': ['KBMSThing'],
          'uri': 'http://example.org/tbox/data',
          'version': '3.2'},
 'DataSet': {'description': 'A specified set of data that is stored in a data store and can be retrieved using a query',
             'label': 'TBox',
             'optional_properties': ['kb:datastore',
                                     'kb:datastoreFormat',
                                     'kb:query',
                                     'kb:queryFormat'],
             'required_properties': [],
             'subclass_of': ['Data'],
             'uri': 'http://example.org/tbox/dataset',
             'version': '3.2'},
 'Document': {'description': 'A data file in a specified format that is human readable or meant to be read by an application as a whole',
              'label': 'TBox',
              'optional_properties': ['dcterms:created', 'kb:URL'],
              'required_properties': [],
              'subclass_of': ['Data'],
              'uri': 'http://example.org/tbox/document',
              'version': '3.2'},
 'KBMSThing': {'description': 'Mother of all knowledge instances',
               'label': 'TBox',
               'optional_properties': ['dcterms:identifier', 'rdfs:type'],
               'required_properties': ['dcterms:description',
                                       'dcterms:title'],
               'subclass_of': [],
               'uri': 'http://example.org/tbox/kbmsthing',
               'version': '3.2'},
 'Organization': {'description': 'Groups of people that collaborate, e.g., companies or development teams',
                  'label': 'TBox',
                  'optional_properties': [],
                  'required_properties': [],
                  'subclass_of': ['Agent'],
                  'uri': 'http://example.org/tbox/organization',
                  'version': '3.2'},
 'Person': {'description': 'People that create knowledge',
            'label': 'TBox',
            'optional_properties': ['foaf:familyName', 'foaf:givenName'],
            'required_properties': [],
            'subclass_of': ['Agent'],
            'uri': 'http://example.org/tbox/person',
            'version': '3.2'},
 'Resource': {'description': 'Anything that does not produce data but is relevant for performing activities and/or creating knowledge',
              'label': 'TBox',
              'optional_properties': [],
              'required_properties': [],
              'subclass_of': ['KBMSThing'],
              'uri': 'http://example.org/tbox/resource',
              'version': '3.2'},
 'System': {'description': 'Systems that can create knowledge, like sensors or software',
            'label': 'TBox',
            'optional_properties': [],
            'required_properties': [],
            'subclass_of': ['Agent'],
            'uri': 'http://example.org/tbox/system',
            'version': '3.2'},
 'User': {'description': 'People that create knowledge and have an account',
          'label': 'TBox',
          'optional_properties': [],
          'required_properties': [],
          'subclass_of': ['Person'],
          'uri': 'http://example.org/tbox/user',
          'version': '3.2'}}

# Dict storing relation info. 
relations = {'contributor': {'description': 'This Agent contributed to this Data item',
                 'from_entity': 'Data',
                 'label': 'object_property',
                 'level': 'upper',
                 'namespace': 'dcterms',
                 'to_entity': 'Agent',
                 'uri': 'http://example.org/tbox/contributor'},
 'hasPart': {'description': 'A related KBMSThing that is included either physically or logically in the described KBMSThing.',
             'from_entity': 'KBMSThing',
             'label': 'object_property',
             'level': 'upper',
             'namespace': 'dcterms',
             'to_entity': 'KBMSThing',
             'uri': 'http://example.org/tbox/haspart'},
 'member': {'description': 'This Person is a member of this Project',
            'from_entity': 'Person',
            'label': 'object_property',
            'level': 'upper',
            'namespace': 'foaf',
            'to_entity': 'Project',
            'uri': 'http://example.org/tbox/member'},
 'references': {'description': 'A related KBMSThing  that is referenced, cited, or otherwise pointed to by the described KBMSThing',
                'from_entity': 'KBMSThing',
                'label': 'object_property',
                'level': 'upper',
                'namespace': 'dcterms',
                'to_entity': 'KBMSThing',
                'uri': 'http://example.org/tbox/references'},
 'related': {'description': 'A relation between two KBMSThings (bi-directional version of references)',
             'from_entity': 'KBMSThing',
             'label': 'object_property',
             'level': 'upper',
             'namespace': 'dcterms',
             'to_entity': 'KBMSThing',
             'uri': 'http://example.org/tbox/related'},
 'requires': {'description': 'A related resource that is required by the described data to support its function, delivery, or coherence',
              'from_entity': 'Data',
              'label': 'object_property',
              'level': 'upper',
              'namespace': 'dcterms',
              'to_entity': 'Resource',
              'uri': 'http://example.org/tbox/requires'},
 'rights': {'description': 'The Document includes  a statement about various property rights associated with the KBMSThing, including intellectual property rights.',
            'from_entity': 'KBMSThing',
            'label': 'object_property',
            'level': 'upper',
            'namespace': 'dcterms',
            'to_entity': 'Document',
            'uri': 'http://example.org/tbox/rights'},
 'rightsHolder': {'description': 'A person or organization owning or managing rights over the KBMSThing',
                  'from_entity': 'KBMSThing',
                  'label': 'object_property',
                  'level': 'upper',
                  'namespace': 'dcterms',
                  'to_entity': 'Agent',
                  'uri': 'http://example.org/tbox/rightsholder'},
 'source': {'description': 'The described Data may be derived from the related Data in whole or in part',
            'from_entity': 'Data',
            'label': 'object_property',
            'level': 'upper',
            'namespace': 'dcterms',
            'to_entity': 'Data',
            'uri': 'http://example.org/tbox/source'},
 'tableOfContents': {'description': 'The related Document contains a list of subunits of the resource',
                     'from_entity': 'Document',
                     'label': 'object_property',
                     'level': 'upper',
                     'namespace': 'dcterms',
                     'to_entity': 'Document',
                     'uri': 'http://example.org/tbox/tableofcontents'},
 'uploader': {'description': 'This Data was uploaded by this User',
              'from_entity': 'Data',
              'label': 'object_property',
              'level': 'upper',
              'namespace': 'kb',
              'to_entity': 'User',
              'uri': 'http://example.org/tbox/uploader'}}

# Dict storing namespace info. 
namespaces = {'dcterms': {'comment': '',
             'uri': 'http://purl.org/dc/terms/',
             'url': 'www.dublincore.org/documents/dcmi-terms/'},
 'foaf': {'comment': '', 'uri': '', 'url': 'http://xmlns.com/foaf/spec/'},
 'kb': {'comment': 'upper / generic terms for knowledge management system',
        'uri': 'tdb: somewhere under MOBI?',
        'url': ''},
 'rdfs': {'comment': '',
          'uri': '',
          'url': 'https://www.w3.org/TR/2014/REC-rdf-schema-20140225/'},
 'stkb': {'comment': 'lower / Simutool specific terms',
          'uri': 'tbd: somewhere under MOBI or under simutool.com?',
          'url': ''}}
